general:
  dump_path: 'dump/dewiktionary-pages-meta-current.xml'
  dump_namespace: 'http://www.mediawiki.org/xml/export-0.10/'

verbs:
  fieldnames:
  - 'Infinitive'
  - 'Pr채sens_ich'
  - 'Pr채sens_du'
  - 'Pr채sens_er, sie, es'
  - 'Pr채teritum_ich'
  - 'Partizip II'
  - 'Konjunktiv II_ich'
  - 'Imperativ Singular'
  - 'Imperativ Plural'
  - 'Hilfsverb'